### ISSUE TITLE
画面遷移でエラーが発生する

### ISSUE THREAD

**Issue by sniper-fly** [sniper-fly/comfortable_diary#16]
<img width="960" alt="2020-05-04 (75)" src="https://user-images.githubusercontent.com/50983271/80943528-61db0f80-8e22-11ea-8d5a-be2d33ee5eb3.png">

画面遷移後に上図のようなエラーが発生する。

コンソールのエラーメッセージは以下。
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building DiaryDetail(dirty):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new Text (package:flutter/src/widgets/text.dart:285:10)
#3      DiaryDetail.build (package:flutterapp/diary_detail.dart:30:22)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by sniper-fly** [comment]
A non-null String must be provided to a Text widget.
のエラーについて調べると、どうやらTextウィジェットに空の値を渡している模様

つまり、DiaryDetail に上手く値が渡せていない

**Comment by sniper-fly** [comment]
自己解決しました。

**Comment by santa112358** [comment]
> A non-null String must be provided to a Text widget.
のエラーについて調べると、どうやらTextウィジェットに空の値を渡している模様
つまり、DiaryDetail に上手く値が渡せていない

その通りです！素晴らしい！
